//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_BusinessObjects.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHILGPSITSERVER\\PHILGPSITSERVER;Initial Catalog=FMS;User ID=app_fms;P" +
            "assword=pa$$fms")]
        public string FMSConnectionString {
            get {
                return ((string)(this["FMSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.96.219.159;Initial Catalog=FMS_V2;Persist Security Info=True;User" +
            " ID=app_fms;Password=pa$$fms")]
        public string FMS_V2ConnectionString {
            get {
                return ((string)(this["FMS_V2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.96.219.159;Initial Catalog=FMS_3;User ID=app_fms;Password=pa$$fms" +
            "")]
        public string FMS_3ConnectionString {
            get {
                return ((string)(this["FMS_3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHILGPSITSERVER\\PHILGPSITSERVER;Initial Catalog=FMS_V2;User ID=app_fm" +
            "s;Password=pa$$fms")]
        public string FMS_V2ConnectionString1 {
            get {
                return ((string)(this["FMS_V2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.96.219.159;Initial Catalog=FMS_3;Persist Security Info=True;User " +
            "ID=app_fms;Password=pa$$fms")]
        public string FMS_3ConnectionString1 {
            get {
                return ((string)(this["FMS_3ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.96.219.159;Initial Catalog=FMS_3;Persist Security Info=True;User " +
            "ID=app_fms;Password=pa$$fms")]
        public string FMS_3ConnectionString2 {
            get {
                return ((string)(this["FMS_3ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.96.219.159;Initial Catalog=FMS_3;Persist Security Info=True;User " +
            "ID=app_fms;Password=pa$$fms")]
        public string FMS_3ConnectionString3 {
            get {
                return ((string)(this["FMS_3ConnectionString3"]));
            }
        }
    }
}
